// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXt4eCcOliL1RQtfKHokI04NTyzn2aNfs',
    appId: '1:181552008900:web:1a1cc5b1c1daa8d7380391',
    messagingSenderId: '181552008900',
    projectId: 'infographica-f379e',
    authDomain: 'infographica-f379e.firebaseapp.com',
    storageBucket: 'infographica-f379e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTj3DeKWAWCqJA2SU5dWSNb_0wjiYlj2Y',
    appId: '1:181552008900:android:fb7415ab9cfd53d0380391',
    messagingSenderId: '181552008900',
    projectId: 'infographica-f379e',
    storageBucket: 'infographica-f379e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApYk1lPzwlTDrvoYhJwwCfOHsYaBNm9MY',
    appId: '1:181552008900:ios:6d954a1c5b428f5f380391',
    messagingSenderId: '181552008900',
    projectId: 'infographica-f379e',
    storageBucket: 'infographica-f379e.firebasestorage.app',
    iosBundleId: 'com.example.infographicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApYk1lPzwlTDrvoYhJwwCfOHsYaBNm9MY',
    appId: '1:181552008900:ios:6d954a1c5b428f5f380391',
    messagingSenderId: '181552008900',
    projectId: 'infographica-f379e',
    storageBucket: 'infographica-f379e.firebasestorage.app',
    iosBundleId: 'com.example.infographicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXt4eCcOliL1RQtfKHokI04NTyzn2aNfs',
    appId: '1:181552008900:web:3547295be2412e34380391',
    messagingSenderId: '181552008900',
    projectId: 'infographica-f379e',
    authDomain: 'infographica-f379e.firebaseapp.com',
    storageBucket: 'infographica-f379e.firebasestorage.app',
  );
}
